import { StyleSheet } from 'react-native';
import { COLORS, SIZES } from '../constants/theme';

const style = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'start',
    alignItems: 'center',
    backgroundColor: COLORS.white,
  },
  imageContainer: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 20,
    marginBottom: 20,
    backgroundColor: COLORS.darkGreen,
  },
  formContainer: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  label: {
    color: COLORS.black,
    fontSize: SIZES.medium,
    fontWeight: 'bold',
    paddingLeft: 10,
    marginBottom: 5,
  },
  textInput: {
    width: 300,
    borderWidth: 1,
    borderRadius: SIZES.large,
    borderColor: COLORS.green,
    backgroundColor: COLORS.gray,
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginBottom: 10,
    fontSize: SIZES.medium,
  },
  submit: {
    width: 300,
    borderWidth: 1,
    borderRadius: SIZES.large,
    borderColor: COLORS.darkGreen,
    backgroundColor: COLORS.darkGreen,
    paddingVertical: 14,
    marginBottom: 10,
  },
  submitText: {
    color: COLORS.white,
    textAlign: 'center',
    fontSize: SIZES.large,
    fontWeight: 'bold',
  },
  link: {
    color: COLORS.darkGreen,
    fontSize: SIZES.large,
    fontWeight: 'bold',
  },
  divider: {
    width: '90%',
    position: 'relative',
    height: 4,
    backgroundColor: COLORS.darkGreen,
    marginVertical: 20,
  },
  dividerText: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -25 }, { translateY: -25 }],
    backgroundColor: COLORS.white,
    width: 50,
    height: 50,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    textAlignVertical: 'center',
    borderRadius: 50,
    color: COLORS.darkGreen,
    fontSize: SIZES.large,
    fontWeight: 'bold',
  },
  iconContainer: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 20,
    alignItems: 'center',
    paddingVertical: 10,
    marginBottom: 10,
  },
  iconBtn: {
    width: 80,
    height: 70,
    borderRadius: 10,
    backgroundColor: COLORS.darkGreen,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default style;
